version: '3'
services:
    app:
        container_name: guru_nest_boilerplate
        build:
            context: .
        hostname: 'docker'
        env_file:
           - .env
        restart: always
        build: .
        ports:
            - '$PORT:$PORT'
        networks:
            guru_network:
                ipv4_address: 99.0.0.2
        volumes:
            - ./src:/app/src
            - /app/node_modules

        entrypoint: []
        command:
            npm run dev
    #     links:
    #         - mariadb
    # mariadb:
    #     image: mariadb
    #     container_name: mariadb
    #     environment:
    #         MYSQL_DATABASE: guru
    #         MYSQL_USER: guru
    #         MYSQL_PASSWORD: guru
    #         MYSQL_ROOT_PASSWORD: root
    #     ports:
    #         - 3306:3306
    #     volumes:
    #         - ./data/db:/var/lib/mysql
    #     networks:
    #         guru_network:
    #             ipv4_address: 99.0.0.2
    # adminer:
    #     image: adminer
    #     restart: always
    #     ports:
    #         - 8080:8080
    #     networks:
    #         guru_network:
    #             ipv4_address: 99.0.0.3

networks:
    guru_network:
        external: true
